### ISSUE TITLE
VS Plugins / Configuration

### ISSUE THREAD

**Issue by james-andrewsmith** [Krusen/PinSharp#1]
I wanted to add support for the Rate Limiting information to be returned. 

It seems I might need to have VS extensions installed to work on the project, can you let me know what they are so I can do a PR?

Thanks

**Comment by Krusen** [comment]
Sorry, didn't get any notification for this.

I don't think you need anything special, but I'll try to have a look if there is anything that is required.

**Comment by Krusen** [comment]
Only thing I think you need is Visual Studio 2015 for some new C#6 features and maybe an XUnit test runner.

**Comment by james-andrewsmith** [comment]
@Krusen Thanks for that - I think it's about time I upgrade to VS2015 and give it a shot!
