### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by FabianZoon** [Krusen/PinSharp#11]
Wrapper works very well. But by updating a Pin I get the following error: System.ObjectDisposedException occurred. [Image of code and exception](https://1drv.ms/i/s!AkSozEt1LohbgbYlmBuyCy17fl1zQw)
But can't figure out why this gives issues.

**Comment by Krusen** [comment]
The request message was being disposed right away for PATCH requests internally.

It should be fixed in v2.2.5 and be on NuGet shortly.

**Comment by FabianZoon** [comment]
Oh thanks!! I did looked in your code, but couldn't see the error. 
I did a pull from Git, and you are correct. It is now working! Thanks, highly appreciated!
