### ISSUE TITLE
Can't find a way to get users pins

### ISSUE THREAD

**Issue by kelzerman** [Krusen/PinSharp#12]
Very nice, but I can't seem to get the pins of other users by username or user id, i.e. Would be very helpful.

**Comment by Krusen** [comment]
Their API is somewhat limited. You will have to know the user name and board name to get any pins.

You can get pins from any public board like this:

```
client.Boards.GetPinsAsync("{username}/{board}");
```

**Comment by kelzerman** [comment]
> Their API is somewhat limited
You don't say ;)

I build some unit tests and it seems to be working. I get 25 pins from a known board. And yes, I know the user name and board name, so that is not a problem.

Thanks for the quick reply!
