### ISSUE TITLE
Create pin from local file

### ISSUE THREAD

**Issue by tomasantunes** [Krusen/PinSharp#13]
Is it possible to create a new pin from a local file?
In the examples the only option is using an URL.

**Comment by Krusen** [comment]
You should be able to do that using the `Pins.CreatePinFromBase64Async(...)` method. You'll have to base64 encode your local file yourself though.

**Comment by tomasantunes** [comment]
I tried using this method but there is no effect and no exception thrown. The status of the pin is "Faulted".

Here is the code I used:
```
var client = new PinSharpClient("xxxxxxxxxxxxxxxx");
var newPin = client.Pins.CreatePinFromBase64Async("user/board", base64str, "note");
Debug.WriteLine(newPin.Status);
```

**Comment by Krusen** [comment]
There's a new version on NuGet (2.2.6). Can you please see if it works with that?

There was an issue with long string (e.g. base64), but I'm not sure if it's related to your issue.

**Comment by tomasantunes** [comment]
It's working now, thanks.
