### ISSUE TITLE
403 error after 45+ GetPinsAsync

### ISSUE THREAD

**Issue by Benjamin124** [Krusen/PinSharp#14]
My issue does not directly concern a method of this project.
This is my code for download my board that contains 3000 pins:

```csharp
var pins = await client.Boards.GetPinsAsync(boardName);
using (var wc = new WebClient())
{
    do
    {
        foreach (var pin in pins)
        {
            var fileName = new Uri(pin.Images.Original.Url).Segments.Last();
            var extension = new FileInfo(fileName).Extension;
            var tempFile = Path.Combine(dir.FullName, pin.Id + extension + ".tmp");
            var destination = Path.Combine(dir.FullName, pin.Id + extension);
            if (File.Exists(tempFile))
                File.Delete(tempFile);
            if (!File.Exists(destination))
            {
                wc.DownloadFile(pin.Images.Original.Url, tempFile);
                File.Move(tempFile, destination);
            }
        }
        pins = await client.Boards.GetPinsAsync(boardName, pins.NextPageCursor);
    } while (pins.Any());
}
```

Work fine until: wc.DownloadFile(pin.Images.Original.Url, tempFile) throw 403 Exception in loop.

Any ideas why pinterest want to block it ? Why only ~1100 pins maximum ?

**Comment by Krusen** [comment]
You are probably triggering some DDoS protection by downloading that many images that fast. It might help if you add a delay between each iteration.

**Comment by Benjamin124** [comment]
Yes it's look like.
I put 2 seconds delay, and except very rare 403, I was able to recover all my board. Thank you for this project ! Any future release ? Like support of sub-board ? :)

**Comment by Krusen** [comment]
Pinterest haven't updated their API, at least not their documentation, so no plans currently.
