### ISSUE TITLE
Is code Works on 2019?

### ISSUE THREAD

**Issue by utherbone** [Krusen/PinSharp#17]
Hello, me program using your nuget package "not work" for me show in debug "Unauthorized".

```
using PinSharp;
using PinSharp.Api;

private async void Button_X(object sender, RoutedEventArgs e)
        {
            // Create a client with your access token
            var client = new PinSharpClient("SECRET_APP");

            // Create new pin
            var newPin = await client.Pins.CreatePinAsync("glopesdasilvasa/testes", "https://i.imgur.com/Q9rcBQo.jpg", "Looks so cool!");
        }
```
I try to create a application to publish in 3 social networks simultaneously, I started with pinterest using the your code.

In app manager on Developers.pinterest.com "App Secret" I copy and past in debuting token and shows not valid. The what this? Interfer to show error "Unathorized"?

Sorry my english is poor

**Comment by Krusen** [comment]
Looks like you are creating the client with your App Secret - you  need to get an Access Token.

```csharp
var authUrl = PinSharpAuthClient.BuildAuthorizationUrl(AppId, RedirectUrl, PinSharp.Api.Scopes.ReadPublic);
```

Go to that `authUrl` and approve that the app can access your stuff. It will then redirect you to your `RedirectUrl` with a query string appended like `?state=xxxxxx&code=89c0dc7470c05faa`.

Use the value of the code query string to get an access token:

```csharp
var code = "89c0dc7470c05faa";
var accessToken = PinSharpAuthClient.GetAccessTokenAsync(AppId, AppSecret, code);
```

Then create the `PinSharpClient` using that access token:

```csharp
var client = new PinSharpClient(accessToken);
```
