### ISSUE TITLE
Access Token ?

### ISSUE THREAD

**Issue by GlennIM** [Krusen/PinSharp#18]
Hi,

Can you please tell me how to get an access token. The link at https://developers.pinterest.com/tools/access_token/ does not work.

Thanks, Glenn

**Comment by Krusen** [comment]
I'm afraid I can't help you. Pinterest doesn't seem to care much about their API. I can't even log in to the developers site.

You can try looking [here](https://developers.pinterest.com/docs/api/overview/) under the **Authentication** section.
