### ISSUE TITLE
Authorization Failed ?

### ISSUE THREAD

**Issue by GlennIM** [Krusen/PinSharp#19]
Here is my code. I have my app set up but get the Authorization Failed exception message when trying to get the boards. Please Advise.

  private async void GetBoardsBTN_ClickAsync(object sender, EventArgs e)
        {
            // Create a client with your access token
            var client = new PinSharpClient("APP SECRET");

            // Get boards of the user associated with the access token
            var boards = await client.Me.GetBoardsAsync(); // Throws Authorization Failed exception
        }

**Comment by Krusen** [comment]
Does the exception contain any message about what is going wrong? Like "expired access token" or something?

**Comment by GlennIM** [comment]
When I catch the exception, the message is only "Authorization Failed". 

I looked at the app and the status says...

In development
You're almost ready! You still need at least 1 collaborator to authorize your app before you can submit. Also, in order to review your app, we require a fully testable implementation and instructions for how to authenticate with your service.

Does this matter?

Under Plateforms...

Site URL is: https://www.spygearco.net
Redirect URIs is greyed out and says... https://localhost/

**Comment by GlennIM** [comment]
Also, can you briefly explain how to (or better yet a short screen cast) create a Pinterest App so that your Api can successfully connect to it and use the functions?

I'm assuming you have to create a Pinterest App for every site you want to use your Api with, correct?

Thanks, Glenn

**Comment by Krusen** [comment]
Looks like you are creating the client with your App Secret - you  need to get an Access Token.

```csharp
var authUrl = PinSharpAuthClient.BuildAuthorizationUrl(AppId, RedirectUrl, PinSharp.Api.Scopes.ReadPublic);
```

Go to that `authUrl` and approve that the app can access your stuff. It will then redirect you to your `RedirectUrl` with a query string appended like `?state=xxxxxx&code=89c0dc7470c05faa`.

Use the value of the code query string to get an access token:

```csharp
var code = "89c0dc7470c05faa";
var accessToken = PinSharpAuthClient.GetAccessTokenAsync(AppId, AppSecret, code);
```

Then create the `PinSharpClient` using that access token:

```csharp
var client = new PinSharpClient(accessToken);
```

**Comment by Krusen** [comment]
`authUrl` will look like this:

```
https://api.pinterest.com/oauth/?response_type=code&client_id=5465468465134153&redirect_uri=https://www.google.dk&scope=read_public&state=a18e845450
```

Open that in a browser.

**Comment by GlennIM** [comment]
Forgive me, I'm a total novice at this...

All I have is my Site URL https://www.spygearco.net

What do I use for the client_id and redirect_uri? Is the client_id the sameas the App ID ?

**Comment by Krusen** [comment]
```csharp
var authUrl = PinSharpAuthClient.BuildAuthorizationUrl(AppId, RedirectUrl, PinSharp.Api.Scopes.ReadPublic);

// authUrl will be something like this:
// https://api.pinterest.com/oauth/?response_type=code&client_id=5465468465134153&redirect_uri=https://www.google.dk&scope=read_public&state=a18e845450
```

Open the return `authUrl` in your browser (log in to Pinterest if not already logged in) and approve your app.

Your browser will then be redirected to the `RedirectUrl` you used earlier (the same have configured in your App settings). At the end of the URL will be a query string appended like `?state=xxxxxx&code=89c0dc7470c05faa`.

Use the value of the `code` parameter to get an access token:

```csharp
var code = "89c0dc7470c05faa";
var accessToken = PinSharpAuthClient.GetAccessTokenAsync(AppId, AppSecret, code);
```

Then create the `PinSharpClient` using that access token:

```csharp
var client = new PinSharpClient(accessToken);
```

**Comment by Krusen** [comment]
The redirect URL is configured here in your App settings:

![image](https://user-images.githubusercontent.com/1381368/55342749-c56d6d80-54a9-11e9-949f-c81d61f624b8.png)

You can enter several URLs if you want. I have set mine to `https://www.google.dk`.

**Comment by GlennIM** [comment]
I'm getting this compiler error for var client = new PinSharpClient(accessToken);

Argument 1: cannot convert from 'System.Threading.Tasks.Task<string>' to 'string'

Also, how does the Pinterest App created relate to the pinterest account?

**Comment by Krusen** [comment]
Sorry, I forgot an `await` in there.

```csharp
var accessToken = await PinSharpAuthClient.GetAccessTokenAsync(AppId, AppSecret, code);
```

**Comment by Krusen** [comment]
The app doesn't relate to the pinterest account. The access token you get is bound to the account you are logged in with, when you visit the `authUrl` and approves that the app can access your information.

**Comment by GlennIM** [comment]
I double checked the code below and put the RedirectURL in the App.

var code = "93bb84390bc55590";
var accessToken = await PinSharpAuthClient.GetAccessTokenAsync("4961064019864599783", "2e12f14e1ff2074c9df2428cabfb5f0cf421a2241855418af915cb1c00c815b5", code);

OK. Now I get this error message...

"Response status code does not indicate success: 401 (Unauthorized)."

- Please advise

**Comment by GlennIM** [comment]
Well I got it to work once. Then tried my code again and now get this error message.

"Response status code does not indicate success: 429 (Too Many Requests)."

What does this mean?

Also, do you execute this URL code https://api.pinterest.com/oauth only once to get the code value?

Also, can the same Pinterest App work for multiple Pinterest accounts?

**Comment by GlennIM** [comment]
I installed this program PostMan and it's a lot easier to create an Access Token to use your API.

Do you recommend using a new Pinterest App for each Pinterest account that is created in order to pin to various boards?

**Comment by Krusen** [comment]
> Also, do you execute this URL code api.pinterest.com/oauth only once to get the code value?

When you have the Access Token you can re-use that until it expires. You should an error when it does, then just repeat the steps you did before to get a new Access Token.

> Also, can the same Pinterest App work for multiple Pinterest accounts?

> Do you recommend using a new Pinterest App for each Pinterest account that is created in order to pin to various boards?

You can use the same App for many users. If you want to test, just log into another account before you visit the `authUrl`.

You will need to create an Access Token for each user and use that one, when pinning to boards that they own.

**Comment by GlennIM** [comment]
I need your input. I got your API working on my end and submitted my App to pinterest and they rejected it. What are the proper steps to get the App accepted by pinterest to allow for the maximum rate limit of calls?

**Comment by Krusen** [comment]
![image](https://user-images.githubusercontent.com/1381368/55672563-b49f6c00-589c-11e9-9c1d-0582ffdb71f3.png)

**Comment by GlennIM** [comment]
Thanks again,

Would you happen to know of an API for C# that can pin to a pinterest account using just the account eMail, Password and Optional Proxy IP? Using an App and trying to get it approved for maximum pinning seems like a real hassle.

-Glenn

**Comment by Krusen** [comment]
I don't I'm sorry.

**Comment by GlennIM** [comment]
Hi Again,

Do I need to have my App approved by Pinterest to use your API? What is the advantages of getting the App approved?

**Comment by Krusen** [comment]
Please, read [Pinterest's developer documentation](https://developers.pinterest.com/docs/api/overview/) or ask them. I'm not in any way affiliated with Pinterest. My library just lets you call their API.

>Effective April 16 2018, all unapproved apps are allowed 10 calls per hour for each unique user token.
>
>After you successfully submit an app for approval, each app (with a unique app ID) is allowed 1000 calls per hour for each unique user token.
>
>In both cases, the 60-minute window is a sliding window based on when you make your first request. If you hit your rate limit, you’ll have to wait a minimum of 1 hour to get a few more requests.
