### ISSUE TITLE
Getting App Approved?

### ISSUE THREAD

**Issue by GlennIM** [Krusen/PinSharp#20]
Hi Again,

Do I need to have my App approved by Pinterest to use your API?

What is the advantages of getting the App approved?

Thanks, Glenn

**Comment by Krusen** [comment]
It's Pinterest's API, not mine.

Before your app is approved you can only do 10 requests per hour.

**Comment by GlennIM** [comment]
Hi Krusen... I'm using your class library with my C# application and Pinterest needs this information for approval... 

"How are you using the API? If you're creating Pins or boards for people, please tell us how with step-by-step instructions."

Can you give me any ideas of what to use for step-by-step instructions to help me get my app approved? I have no clue.

Thanks, Glenn

**Comment by Krusen** [comment]
No. Go read their documentation, terms and policies etc.

![image](https://user-images.githubusercontent.com/1381368/56045403-7a711700-5d41-11e9-8c0d-bca376fae5e5.png)
