### ISSUE TITLE
Board Not Found

### ISSUE THREAD

**Issue by GlennIM** [Krusen/PinSharp#21]
I'm calling var newPin = await client.Pins.CreatePinAsync() and the response says that the board is not found, yet I was able to iterate through the boards and the one listed in my list is the exact name I used to pin an image.

Do I have to prefix the board name with something?

Thanks, Glenn

**Comment by Krusen** [comment]
You have to use this format `{user}/{board}`

**Comment by GlennIM** [comment]
I used... "Pinterest Username/My Board Name" and still get "Board Not Found" but if I use the Board ID string  the method works OK. So I'll just stick with using the Board ID string I guess.
