### ISSUE TITLE
Using with Desktop client (Winform/WPF)

### ISSUE THREAD

**Issue by rajputs6** [Krusen/PinSharp#22]
Please suggest how can we use it with Winform /wpf client . What will be code value in this case for PinSharpAuthClient.GetAccessTokenAsync

**Comment by Krusen** [comment]
1. Build an authorization URL.

```csharp
var authUrl = PinSharpAuthClient.BuildAuthorizationUrl("your-client-id", "https://your-site.com", PinSharp.Api.Scopes.ReadPublic);
```

2. Have your user open that URL in a browser.
- It will ask him to approve that your app can access his data.
- He will then be redirected to the provided redirect URL with a code in the query string, 
e.g. `https://your-site.com/?code=XXXXXXXXXXX`

3. Get the access token using the code received from step 2.

```csharp
var accessToken = PinSharpAuthClient.GetAccessTokenAsync("your-client-id", "your-client-secret", code);
```
