### ISSUE TITLE
Invalid Parameters

### ISSUE THREAD

**Issue by GlennIM** [Krusen/PinSharp#25]
I have been using your wonderful library for months now with no problems. But now every time I call the function below, PinSharp throws and "Invalid Parameters" Exception. What is wrong?

await pinSharpClient.Pins.CreatePinAsync()

Here are the values I'm passing to it...

BoardID = "469289292360076140"

Image =   "https://www.selfdefensegearco.com//Images/CuttingEdgeProducts/large_1592_SWM2BKspark_P.jpg"

Description = "Just recently females have actually been motivated to stand and speak up versus unwanted sexual advances and abuse. The #MeToo motion - which initially started in 2006 - has actually contributed in leading the charge in this location. Given that 1990 - nevertheless - Streetwise Security Products has actually likewise been leading the charge by manu ...  #selfdefenseforwomen #selfdefenseweaponsforwomen #selfdefensetoolsforwomen #bestselfdefenseforwomen #selfdefenseitemsforwomen #selfdefensetechniquesforwomen #bestgunforwomensselfdefense #selfdefenseequipmentforwomen #selfdefensestepsforwomen #selfdefensegunsforwomen #selfdefensetacticsforwomen #basicselfdefenseforwomen #bestselfdefensepistolforwomen #selfdefenseforwomenmagazine #selfdefenseforwomenrunners"

Pin Link: "https://www.selfdefensegearco.com/StreetwiseMeToo23MillionVoltStunGun.htm"

**Comment by TheMirzai** [comment]
Looks like the Creator field has now been deprecated - https://developers.pinterest.com/docs/api/boards/

**Comment by GlennIM** [comment]
Can you fix PinSharp to account for this?

**Comment by Krusen** [comment]
I've removed the 'creator' property and pushed it to NuGet as version 2.3.0.

I haven't tested it so please let me know if it works.

**Comment by GlennIM** [comment]
Installed 2.3.0 and still get the same exception... "Invalid Parameters"

Exception thrown: 'PinSharp.Api.Exceptions.PinSharpBadRequestException' in mscorlib.dll
The thread 0x2120 has exited with code 0 (0x0).
The thread 0x1af8 has exited with code 0 (0x0).
The thread 0x2464 has exited with code 0 (0x0).
The thread 0x1f18 has exited with code 0 (0x0).
Exception thrown: 'PinSharp.Api.Exceptions.PinSharpBadRequestException' in mscorlib.dll

-Please advise

**Comment by Krusen** [comment]
Could you please also post the values of `Message` and `ResponseContent` properties from the exception?

**Comment by GlennIM** [comment]
Message: "Invalid parameters."
ResponseContent: "{\"message\": \"Invalid parameters.\", \"type\": \"api\", \"param\": \"creator\"}"
RequestUrl: "https://api.pinterest.com/v1/pins/?fields=id,url,link,note,attribution,original_link,color,board,counts,created_at,creator(id,url,first_name,last_name,username,image),image,media,metadata"

I rebuilt my project and make sure it's version 2.3.0 of PinSharp

**Comment by Krusen** [comment]
I've published a new version removing some leftover references to the 'creator' field (putting it in the request URL) which should fix the issue.

**Comment by GlennIM** [comment]
EXCELLENT Soren...

Works again. **Thank you VERY Much**.

I'm planning on using your wonderful library in other projects because it seems to be the only C# wrapper for the Pinterest API and is VERY well designed. If I or others encounter issues or problems in the future, will you be able to address them going forward?

-Glenn

**Comment by Krusen** [comment]
Good to hear.

I'll most likely be able to help with any bugs in the future, but it will not always be my highest priority as I'm not using this myself and it's free.

**Comment by GlennIM** [comment]
Thanks Soren,

I'f I find a problem in the future and you don't have the time to address it, can I install your solution/project in my application and find and make the changes to get it working again? How complex is your code?

Thanks, Glenn
