### ISSUE TITLE
Create pin api is failing

### ISSUE THREAD

**Issue by leventeolahx** [Krusen/PinSharp#29]
CreatePinAsync fails most of the times with an error message: "Unexpected character encountered while parsing value: \u001f. Path '', line 0, position 0."

However the post is published.

I could not managed to find a clearly way how to reproduce it. A specific request just simply fails in one time but in the next try works again.

I was debugging it and seems that the response has a wrong encoding.

**Comment by imjustalf** [comment]
I'm also seeing this issue as of this morning. Similar behavior, api gives an error but the pin is created.

**Comment by Krusen** [comment]
Seems like Pinterest decided to Gzip at least some of the responses, which the `HttpClient` doesn't decompress by default.

It should be fixed in v2.3.3 - available on NuGet shortly.
