### ISSUE TITLE
How to Catch API Rate Limit Exception using PinSharp

### ISSUE THREAD

**Issue by GaneshNayakK** [Krusen/PinSharp#4]
Hi,

How to catch API Rate Limit Exception? We have PinterestAPIException block, but whenever rate limit exceeds this will hit to Generic catch block and shows exception message as "Value cannot be null".

Please let me know how to check Current Limit, Remaining Limit using PinSharp.

**Comment by Krusen** [comment]
There is currently no way to do that.

Months ago I was working on a new version which had rate limit information and more specific exceptions, but I never got around to finishing it.

I'll take a look at it and see if I can finish it or release a prerelease version on NuGet in its current state.

**Comment by GaneshNayakK** [comment]
Thanks for your quick reply.

**Comment by Krusen** [comment]
I've released 2.0.0-RC1 on NuGet. You have to enable installing prereleases to be able to see it/install it.

There's a lot of breaking changes which you can [read about in the updated readme](https://github.com/Krusen/PinSharp/blob/master/README.md#new-in-version-20).

Please give it a go and let me know how it goes or if you need help with anything.
