### ISSUE TITLE
error on fetching  pin from a board

### ISSUE THREAD

**Issue by mabolhasani** [Krusen/PinSharp#7]
Hi

when i am trying to fetch pins from board named deepthr3e/virtual-reality-video-gaming I found that when fetching a specific pin the exception thrown "Error reading string. Unexpected token: StartObject. Path 'attribution.embed', line 1, position 425."   i investigate the error and found that the issue
in the specific pin we have an object named "Attribution" and in this object have an object named "embed 
"and your code doesn't have this object 
here an image of the hierarchy of the json of pins [https://s3.postimg.org/gui81hpyb/Capture.png](url)

this is the full address of board: https://www.pinterest.com/abolhasani1149/error-board/
and this is the very pin that causes the issue: https://www.pinterest.com/pin/679128818779898527/

**Comment by Krusen** [comment]
Thanks for letting me know. I'll take a look.

**Comment by Krusen** [comment]
According to their documentation the `attribution` element is supposed to be `map<string,string>` but in this case `embed` is an `object` and not a `string`.

2.0.1 will be available on NuGet shortly.

**Comment by mabolhasani** [comment]
Thank you
