### ISSUE TITLE
Need API Details for reference

### ISSUE THREAD

**Issue by nilesh-shah** [Krusen/PinSharp#8]
Hello @Krusen 
I am reaching out to you to get some better details on Pinterest API. I am looking for an API from Pinterest which gives me the list of users against a specific search criteria and list of boards against specific search criteria. Do you know if such APIs exist? I am trying hard to get accurate answer here. Please note that, my application cannot generate token for each users. So I will be generating the token once with required scopes and interested in getting list of valid users and boards (public boards from other users).

I am also observing that the stackoverflow community talks about V2 and V3 APIs from pinterest, but i am not seeing any details. Is it like pinterest will be launching new API version in near future? Please let me know if you have any insight on this.

Thanks
Nilesh

**Comment by Krusen** [comment]
Their API documentation is a bit lacking and not always 100% correct. They also don't seem to be developing it that much.

You cannot search for users or boards. You can only get a list of boards and other info about your own user (the one used to create the access token). You can of course get public pins and boards of other users but you have to now the names of both.

You can find their documentation here: https://developers.pinterest.com/docs/getting-started/introduction/
