### ISSUE TITLE
Question: Pinning limits

### ISSUE THREAD

**Issue by surewood** [Krusen/PinSharp#9]
Hi,

awesome job on the library. I was able to pin stuff very quickly.

I'd like to automatically pin certain blog posts every day. The maximum number of daily pins would be 10. Do you, by any chance, have an idea if this is agains TOS? Don't want to get banned.

**Comment by Krusen** [comment]
I honestly don't know, but if it is possible through the API I don't see why it wouldn't be allowed.

**Comment by surewood** [comment]
Great. I'm not going to overdo it, otherwise I will definitively get banned.
